USE [master]
GO
/****** Object:  Database [Estoque]    Script Date: 19/08/2020 02:41:25 ******/
CREATE DATABASE [Estoque]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Estoque', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estoque.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Estoque_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Estoque_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Estoque] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Estoque].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Estoque] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Estoque] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Estoque] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Estoque] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Estoque] SET ARITHABORT OFF 
GO
ALTER DATABASE [Estoque] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Estoque] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Estoque] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Estoque] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Estoque] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Estoque] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Estoque] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Estoque] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Estoque] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Estoque] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Estoque] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Estoque] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Estoque] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Estoque] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Estoque] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Estoque] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Estoque] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Estoque] SET RECOVERY FULL 
GO
ALTER DATABASE [Estoque] SET  MULTI_USER 
GO
ALTER DATABASE [Estoque] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Estoque] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Estoque] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Estoque] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Estoque] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Estoque', N'ON'
GO
ALTER DATABASE [Estoque] SET QUERY_STORE = OFF
GO
USE [Estoque]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](128) NOT NULL,
	[UnitPrice] [decimal](18, 2) NULL,
	[Amount] [int] NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[P_Product_Delete]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_Product_Delete]
(
	@Id AS INT
)
AS
BEGIN
	DELETE FROM Product
	WHERE @Id = Id
END
GO
/****** Object:  StoredProcedure [dbo].[P_Product_Get]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_Product_Get]
(
	@Id AS INT
)
AS
BEGIN
	SELECT *
	FROM Product
	WHERE @Id = Id
END
GO
/****** Object:  StoredProcedure [dbo].[P_Product_GetAll]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[P_Product_GetAll]
AS
BEGIN
	SELECT *
	FROM Product
END
GO
/****** Object:  StoredProcedure [dbo].[P_Product_Insert]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_Product_Insert]
(
	@Name AS VARCHAR(128),
	@UnitPrice AS DECIMAL(18,2),
	@Amount AS INT
)
AS
BEGIN
	INSERT INTO [dbo].[Product]([Name],[UnitPrice],[Amount])
     VALUES (@Name, @UnitPrice, @Amount)
END
GO
/****** Object:  StoredProcedure [dbo].[P_Product_Update]    Script Date: 19/08/2020 02:41:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_Product_Update]
(
	@Id AS INT,
	@Name AS VARCHAR(128),
	@UnitPrice AS DECIMAL(18,2),
	@Amount AS INT
)
AS
BEGIN
	UPDATE [dbo].[Product]
	SET [Name] = @Name, 
		[UnitPrice] = @UnitPrice,
		[Amount] = @Amount
	WHERE @Id = Id
END
GO
USE [master]
GO
ALTER DATABASE [Estoque] SET  READ_WRITE 
GO
